---
version: "3.1"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=13001
      - PGID=13000
      - UMASK=002
      - TZ=Europe/Amsterdam
    volumes:
      - /home/user/ezarr/config/sonarr-config:/config
      - /home/user/ezarr/data:/data
    ports:
      - "8989:8989"
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=13002
      - PGID=13000
      - UMASK=002
      - TZ=Europe/Amsterdam
    volumes:
      - /home/user/ezarr/config/radarr-config:/config
      - /home/user/ezarr/data:/data
    ports:
      - "7878:7878"
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=13012
      - PGID=13000
      - TZ=Europe/Amsterdam
    volumes:
      - /home/user/ezarr/config/bazarr-config:/config
      - /home/user/ezarr/data/media:/media
    ports:
      - "6767:6767"
    restart: unless-stopped

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=13003
      - PGID=13000
      - UMASK=002
      - TZ=Europe/Amsterdam
    volumes:
      - /home/user/ezarr/config/lidarr-config:/config
      - /home/user/ezarr/data:/data
    ports:
      - "8686:8686"
    restart: unless-stopped

  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=13004
      - PGID=13000
      - UMASK=002
      - TZ=Europe/Amsterdam
    volumes:
      - /home/user/ezarr/config/readarr-config:/config
      - /home/user/ezarr/data:/data
    ports:
      - "8787:8787"
    restart: unless-stopped

  mylar3:
    image: lscr.io/linuxserver/mylar3:latest
    container_name: mylar3
    environment:
      - PUID=13005
      - PGID=13000
      - UMASK=002
    volumes:
      - /home/user/ezarr/config/mylar-config:/config
      - /home/user/ezarr/data:/data
    ports:
      - "8090:8090"
    restart: unless-stopped

  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    environment:
      - AUDIOBOOKSHELF_UID=13009
      - AUDIOBOOKSHELF_GID=13000
    volumes:
      - /home/user/ezarr/config/audiobookshelf:/config
      - /home/user/ezarr/data/audiobooks:/audiobooks
      - /home/user/ezarr/data/podcasts:/podcasts
      - /home/user/ezarr/data/metadata:/metadata
    ports:
      - "13378:80"
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=13006
      - PGID=13000
      - UMASK=002
      - TZ=Europe/Amsterdam
    volumes:
      - /home/user/ezarr/config/prowlarr-config:/config
    ports:
      - "9696:9696"
    restart: unless-stopped

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=13010
      - PGID=13000
      - VERSION=docker
      - PLEX_CLAIM=
    volumes:
      - /home/user/ezarr/config/plex-config:/config
      - /home/user/ezarr/data/media:/media
    restart: unless-stopped

  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    depends_on:
      - plex
    environment:
      - PUID=${UID}
      - PGID=13000
      - TZ=Europe/Amsterdam
    volumes:
      - /home/user/ezarr/config/tautulli-config:/config
    ports:
      - "8181:8181"
    restart: unless-stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=${UID}
      - PGID=13000
      - UMASK=002
      - TZ=Europe/Amsterdam
    volumes:
      - /home/user/ezarr/config/jellyfin-config:/config
      - /home/user/ezarr/data/media:/data
    ports:
      - "8096:8096"
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=13007
      - PGID=13000
      - UMASK=002
      - TZ=Europe/Amsterdam
      - WEBUI_PORT=8080
    volumes:
      - /home/user/ezarr/config/qbittorrent-config:/config
      - /home/user/ezarr/data/torrents:/data/torrents
    ports:
      - "8080:8080"
      - "6881:6881"
      - "6881:6881/udp"
    restart: unless-stopped

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=13011
      - PGID=13000
      - UMASK=002
      - TZ=Europe/Amsterdam
    volumes:
      - /home/user/ezarr/config/sabnzbd-config:/config
      - /home/user/ezarr/data/usenet:/data/usenet
    ports:
      - "8081:8080"
    restart: unless-stopped
